### ISSUE TITLE
Does not function on Gnome Shell 3.6 (Ubuntu GNOME 13.04)

### ISSUE THREAD

**Issue by RavanH** [l300lvl/overview-on-startup-extension#1]
Installed via extensions.gnome.org on a fresh Ubuntu GNOME 13.04 running Gnome Shell 3.6

No errors are reported...

**Comment by Baltix** [comment]
Doesn't work on GNOME Shell 3.4 (Ubuntu 12.04 LTS) - installed via extensions.gnome.org :(

**Comment by l300lvl** [comment]
unsure why

**Comment by RavanH** [comment]
Currently, I'm on Gnome Shell 3.12.2-1ubuntu7 (Ubuntu 14.10) and it's not working there either... Any logs we should check for errors or debug messages?

**Comment by RavanH** [comment]
Update: in Shell Looking Glass, I see the extension has en error reported:

TypeError: showView._viewSelector is undefined

**Comment by RavanH** [comment]
Update 2: turns out the above error is the result of the ._viewSelector for above .4 which should be .viewSelector without the underscore. Remove the underscore and the error has gone. But not the real issue...

If I run Main.overview.show() in the Looking Glass Eveluator tab, the overview comes up just fine. So somehow Main.overview.show(); is failing at the moment .local/share/gnome-shell/extensions/overview-on-startup@atz3.yahoo.com/extension.js is actually run. But it seems to fail silently :(

**Comment by l300lvl** [comment]
i think i understnd. i can change that i just expected no one to be using 3.12(edit:i was thinking of 3.2 when i typed this NOT 3.12, i never updated ANY of my work for 3.12 but i will check that out) anymore since its not officially supported by gnome, but thats ok. i will update with the info you provided to make it work.

is there any way you can tell me if this appears on 3.12.0 or lower than 3.12.2? i ask as this works fine on the 3.12 version i tested with (openSuse)

**Comment by l300lvl** [comment]
i see you are commenting about multiple versions. im not sure i use the same code in 3.4 OR 3.6, but ill check that too. certain functions wont be available in those, every shell release has a core change that affects almost all extensions.

**Comment by l300lvl** [comment]
OK. So some of the confusion I had was I originally wrote this to be very basic and support every version possible. If you check the code here https://extensions.gnome.org/review/2793

You will see this version will work on ANY shell version, since it only opens the main overview and nothing more, nothing less. It will never fail. What I would like to do is give the option to use this method by default regardless of the version, so it will always work. Someone else forked this extension though, and their changes will probably be more suitable to most people, actually I like them myself.

But, since the original writeup I made will still work on every possible version for now I will rebase off of that, and make that the default option so it can't totally fail when code changes in minor .1/.01/.12 etc versions.

Apologies for all the confusion!

**Comment by l300lvl** [comment]
the culprit is this should be set to no by default, so it will need recompiled as well:

https://github.com/l300lvl/overview-on-startup-extension/blame/7a7f5b786eb4ad91f9491bdbf78d29722fbc3def/overview-on-startup%40atz3.yahoo.com.v6.shell-extension/schemas/org.gnome.shell.extensions.overviewonstartup.gschema.xml

**Comment by l300lvl** [comment]
@RavanH do you still have a 3.4 shell installed, maybe you can test something for me? I'm wondering if you meant that 3.4 has NO ._viewSelector at all, or it actually does but without the underscore?

I can verify on 3.15.92 that this seems different from 3.10 and 3.8 on openSuse where it DID work with the underscore. I amm going to try it the other way now though, and if it works without it that was possibly a problem all along.

Can you try running this from lg:

> Main.overview.show(); Main.overview.viewSelector._showAppsButton.checked = true

**Comment by RavanH** [comment]
I'm running GNOME Shell 3.12.2 and it has a viewSelector but without underscore. And like I stated before, the commands from lg as you give them also, work fine.

Still, the zip I downloaded this morning here from Github is not working. Had to add 3.12 to the supported versions to activate and lg reports no errors. If I restart shell, overview does not open. I removed the underscore and still nothing ... but if I then go to the overview manually, the first time it opens in the Apps view. So I suppose the ...overview.viewSelector._showAppsButton.checked = true; did get set in the background.

But then I can not imagine why ...overview.show(); would fail silently...

**Comment by l300lvl** [comment]
do you have any apps set to startup when you login? this will surely cause this behavior, as this checks for no apps having focus when the shell launches, in 3.10 and lower focus wasn't given to any apps open on shell startup until you clicked an app, so this was a non issue for me.

it could very well be something other though.

i will try to find a way around that and possibly other ways, as it stands though someone has forked my extension and it can be found here: https://github.com/simonthechipmunk/jumptooverview and here: https://extensions.gnome.org/extension/895/jump-to-overview/

this will work probably without a hitch and offers other features as well, i had to find it again sorry it took some time, but i still wish to learn a few things on my own as to why it isnt working. im no expert at this, so sorry if i cant be of the utmost assistance in solving the issue. eventually i will work it out as im trying to keep my solutions a bit simpler with less code than simon has used, so with a few changes i believe i can adapt his solutions to fit my methodology.

**Comment by RavanH** [comment]
Less code? I'm a fan :+1: 

I don't have any apps at startup (at least none are reported by Gnome Tweaks > Startup Applications) but I do have the option "Keep backgroud apps running" checked in Chromium. I'll test if that explains the behaviour...

**Comment by RavanH** [comment]
UPDATE: disabled background apps in chromium and all other shell extensions but still the overview does not open on start.

**Comment by l300lvl** [comment]
interesting. thank you for the feedback. im downloading ubuntu 14.10 myself to check this out, but in the mean time perhaps you can try something for me? this is the very first version of this, on extensions.gnome.org: https://extensions.gnome.org/review/download/2793.shell-extensiton.zip

if you could download that and install it the way youve been, you'll have to update the metadata to your shell version again, but this could be helpful. if you can, once you have it enabled and have restarted the shell already, open a terminal and run gnome-shell --replace and then when it restarts post the output here for me? or send it to me in an email to the address found here on github, or even using the bug report tool on ego...perhaps that will shed more light on this issue before i get to run 14.10 myself.

**Comment by RavanH** [comment]
~~I'm afraid the zip dowload link lands me on a 404 page...~~ OK found the correct zip/download location. Will test.

I the mean time the output shortly after `gnome-shell --replace` with the latest version:

`Gjs-Message: JS LOG: No permission to trigger offline updates: Polkit.Error: GDBus.Error:org.freedesktop.PolicyKit1.Error.Failed: Action org.freedesktop.packagekit.trigger-offline-update is not registered
Gjs-Message: JS LOG: GNOME Shell started at Mon Mar 23 2015 10:22:14 GMT+0100 (CET)
Gjs-Message: JS LOG: pushModal: invocation of begin_modal failed
Waarschuwing van vensterbeheer:Log level 16: /build/buildd/glib2.0-2.42.1/./gobject/gsignal.c:3101: signal id '596' is invalid for instance '0x3542050'`

**Comment by RavanH** [comment]
And after installing v1:

`Gjs-Message: JS LOG: No permission to trigger offline updates: Polkit.Error: GDBus.Error:org.freedesktop.PolicyKit1.Error.Failed: Action org.freedesktop.packagekit.trigger-offline-update is not registered
Gjs-Message: JS LOG: GNOME Shell started at Mon Mar 23 2015 10:42:17 GMT+0100 (CET)
Gjs-Message: JS LOG: pushModal: invocation of begin_modal failed`

**Comment by RavanH** [comment]
And after disabling the extension:

`Gjs-Message: JS LOG: No permission to trigger offline updates: Polkit.Error: GDBus.Error:org.freedesktop.PolicyKit1.Error.Failed: Action org.freedesktop.packagekit.trigger-offline-update is not registered
Gjs-Message: JS LOG: GNOME Shell started at Mon Mar 23 2015 10:50:20 GMT+0100 (CET)
Waarschuwing van vensterbeheer:Log level 16: /build/buildd/glib2.0-2.42.1/./gobject/gsignal.c:3101: signal id '596' is invalid for instance '0x449f500'`

**Comment by simonthechipmunk** [comment]
finally. I just talked to some folks on the gnome IRC and maybe found a solution to this: #3 
Good thing though this didn't take me too long or anything... just six months... ughh, sorry :)

**Comment by RavanH** [comment]
Hi Simon, that's excellent news no matter how long it took ! ;) I'm on Ubuntu GNOME 15.04 and try to install the extension again...

**Comment by l300lvl** [comment]
i have just merged the changes from @simonthechipmunk so hopefully this does it. sorry it took me so long as well, im closing this for now. note i still havent updated to e.g.o yet.
